### ISSUE TITLE
Allow overriding `extra_size` for given fields in derive macro

### ISSUE THREAD

**Issue by aecsocket** [GnomedDev/typesize#4]
Similar to `datasize`, the derive macro should be able to take a `#[type_size(with = ..)]` or similar, which defines the function to use for computing the `extra_size` of a given field. This lets you derive `TypeSize` on types which store fields that aren't `TypeSize` themselves, or for which you need some unique logic.

**Comment by GnomedDev** [comment]
We have already got `typesize(skip)` for the basic case, but I agree that this should be added.

**Comment by aecsocket** [comment]
Ah didn't notice `skip`, it didn't show up in the docs here for 0.1.9: https://docs.rs/typesize/latest/typesize/derive/derive.TypeSize.html. That might work for some of my use cases. Still, `with` would also be useful.

**Comment by GnomedDev** [comment]
It isn't on crates.io yet, yeah.
